version: "3.9"
services:
  web:
    build: .
    container_name: "docker_flask_server"
    hostname: "docker_flask_server"
    ports:
      - "8990:8990"
    links:
      - "solr:docker_solr"
    networks:
        default:
            aliases:
                - custom_network
  solr:
    container_name: "docker_solr"
    hostname: "docker_solr" 
    image: "solr:8.9.0"
    ports:
     - "8983:8983"
    command:
      - solr-precreate
      - base_core
    networks:
        default:
            aliases:
                - custom_network

